name: eldera
description: A comprehensive health monitoring mobile application for elderly care.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.6.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  image_picker: ^1.1.2
  flutter_gemini: ^2.0.5
  http: ^1.2.2
  path_provider: ^2.1.4
  audioplayers: ^6.1.0
  timezone: ^0.9.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^17.2.2
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  device_calendar: ^4.3.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  supabase_flutter: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/eldera_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2d7d7d"
  adaptive_icon_foreground: "assets/images/eldera_logo.png"
